version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  next:
    container_name: next
    build:
      context: ../infra/containers/node
      dockerfile: Dockerfile
    volumes:
      - ./chart-app:/usr/src/app
    command: bash -c "yarn dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    logging: *default-logging
