.npm_build_default: &npm_build_default
  stage: build
  image: node:14
  artifacts:
    paths:
      - frontend/src/node_modules/

npm-build:
  <<: *npm_build_default
  script:
    - yarn cache clean && yarn install --no-optional
    - cd frontend/src
#    - npm build build-$CI_BUILD_REF_NAME
    - yarn build
  only:
    - develop
    - master
