# Generated by Django 3.1.3 on 2020-11-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('market_products_kubun', models.CharField(max_length=200, verbose_name='市場・商品区分')),
                ('industries_code', models.IntegerField(verbose_name='業種コード')),
                ('industries_kubun', models.CharField(max_length=200, verbose_name='業種区分')),
                ('detailed_industries_code', models.IntegerField(verbose_name='詳細業種コード')),
                ('detailed_industries_kubun', models.CharField(max_length=200, verbose_name='詳細業種区分')),
                ('scale_code', models.IntegerField(verbose_name='規模コード')),
                ('scale_kubun', models.CharField(max_length=200, verbose_name='規模区分')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'company_table',
                'db_table': 'company_table',
            },
        ),
        migrations.CreateModel(
            name='RawPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='銘柄コード')),
                ('date', models.DateField(verbose_name='日付')),
                ('datetime', models.DateTimeField(verbose_name='日時')),
                ('open_price', models.IntegerField(verbose_name='始値')),
                ('close_price', models.IntegerField(verbose_name='終値')),
                ('high_price', models.IntegerField(verbose_name='高値')),
                ('low_price', models.IntegerField(verbose_name='安値')),
                ('volume', models.IntegerField(verbose_name='出来高')),
                ('adjustment_close_price', models.FloatField(verbose_name='調整後終値')),
                ('moving_averages25', models.FloatField(verbose_name='25日移動平均線')),
                ('moving_averages75', models.FloatField(verbose_name='75日移動平均線')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
