# Generated by Django 3.1.3 on 2020-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20201109_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawprices',
            name='adjustment_close_price',
        ),
        migrations.RemoveField(
            model_name='rawprices',
            name='datetime',
        ),
        migrations.AddField(
            model_name='rawprices',
            name='moving_averages100',
            field=models.FloatField(null=True, verbose_name='100日移動平均線'),
        ),
        migrations.AddField(
            model_name='rawprices',
            name='moving_averages200',
            field=models.FloatField(null=True, verbose_name='200日移動平均線'),
        ),
        migrations.AddField(
            model_name='rawprices',
            name='moving_averages5',
            field=models.FloatField(null=True, verbose_name='5日移動平均線'),
        ),
        migrations.AlterField(
            model_name='rawprices',
            name='moving_averages25',
            field=models.FloatField(null=True, verbose_name='25日移動平均線'),
        ),
        migrations.AlterField(
            model_name='rawprices',
            name='moving_averages75',
            field=models.FloatField(null=True, verbose_name='75日移動平均線'),
        ),
        migrations.AddConstraint(
            model_name='rawprices',
            constraint=models.UniqueConstraint(fields=('code', 'date'), name='unique_booking'),
        ),
    ]
