# Generated by Django 3.1.3 on 2020-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20201115_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawprices',
            name='volume',
            field=models.BigIntegerField(verbose_name='出来高'),
        ),
    ]
