# Generated by Django 3.1.2 on 2020-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
            ],
        ),
        migrations.CreateModel(
            name='RawPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='銘柄コード')),
                ('date', models.DateField(verbose_name='日付')),
                ('open_price', models.IntegerField(verbose_name='始値')),
                ('close_price', models.IntegerField(verbose_name='終値')),
                ('high_price', models.IntegerField(verbose_name='高値')),
                ('low_price', models.IntegerField(verbose_name='安値')),
                ('volume', models.IntegerField(verbose_name='出来高')),
                ('adjustment_close_price', models.FloatField(verbose_name='調整後終値')),
                ('moving_averages25', models.FloatField(verbose_name='25日移動平均線')),
                ('moving_averages75', models.FloatField(verbose_name='75日移動平均線')),
            ],
        ),
    ]
