# Generated by Django 3.1.2 on 2020-10-26 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawprices',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時'),
            preserve_default=False,
        ),
    ]
