# Generated by Django 3.1.2 on 2020-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20201031_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'company_table'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='company_table',
        ),
    ]
