apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
        - args:
            - bash
            - -c
            - yarn dev
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          image: node
          name: node
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: node-claim0
      restartPolicy: Always
      volumes:
        - name: node-claim0
          persistentVolumeClaim:
            claimName: node-claim0
status: {}
