#!/usr/bin/env bash
git secrets --pre_commit_hook -- "$@"

if [ "$OS" = "Windows_NT" ]; then
    wsl.exe docker start node
    wsl.exe docker exec -t node yarn lint --fix
    wsl.exe docker exec -t node yarn test
    #wsl.exe docker exec -t node yarn storyshots
    #wsl.exe docker exec -t node yarn puppeteer-storyshots
else
    docker start node
    docker exec -t node yarn lint --fix
    docker exec -t node yarn test
    #docker exec -t node yarn storyshots
    #docker exec -t node yarn puppeteer-storyshots
fi
