name: Run django test

on: [push]

jobs:
  back_build:
    # 実行するインスタンス
    runs-on: ubuntu-latest
    # pythonのバージョン一覧
    strategy:
      matrix:
        python-version: [ '3.8' ]
    env:
      DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      DATABASE_DB: django_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      CACHE_ENGINE: django_redis.cache.RedisCache
      CACHE_LOCATION: redis://cache:6379/
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      # チェックアウト
      - uses: actions/checkout@v1

      # 使用するpythonのバージョンを指定
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev

      - name: Install pipenv and dependencies
        run: |
          cd backend/containers/django
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --skip-lock

      - name: Run migrations and test
        run: |
          cd backend/containers/django
          python3 manage.py migrate
          python3 manage.py test
